[package]
name = "mcp"
version.workspace = true
edition.workspace = true

[dependencies]
auth = { workspace = true }
blob = { workspace = true }
domain = { workspace = true }
proto = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
store = { workspace = true }
sync = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
uuid = { workspace = true }
